name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rakudo & zef
        uses: Raku/setup-raku@v1

      - name: Install deps
        run: zef install --/test . --depsonly

      - name: Install FreeFont (attempt, optional)
        run: sudo apt-get update && sudo apt-get install -y fonts-freefont-ttf || true

      - name: Run tests
        run: zef test .

      - name: Package source bundle
        run: |
          mkdir -p dist
          zip -r dist/gnu-freefont-addon-src.zip lib bin t README* META6.json .github Makefile 2>/dev/null || true

      - name: Generate sample PDFs (best-effort)
        run: |
          mkdir -p dist
          if [ -f /usr/share/fonts/truetype/freefont/FreeSerif.ttf ]; then             raku bin/make-freefont-samples.raku --font-ref=/usr/share/fonts/truetype/freefont/FreeSerif.ttf --out=dist/freefont-serif-samples.pdf ;           fi
          if [ -f /usr/share/fonts/truetype/freefont/FreeSans.ttf ]; then             raku bin/make-freefont-samples.raku --font-ref=/usr/share/fonts/truetype/freefont/FreeSans.ttf --out=dist/freefont-sans-samples.pdf ;           fi
          if [ -f /usr/share/fonts/truetype/freefont/FreeMono.ttf ]; then             raku bin/make-freefont-samples.raku --font-ref=/usr/share/fonts/truetype/freefont/FreeMono.ttf --out=dist/freefont-mono-samples.pdf ;           fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gnu-freefont-addon-artifacts
          path: dist/*

  release:
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: gnu-freefont-addon-artifacts
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
